/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  CountryCode,
} from 'libphonenumber-js';

export namespace Components {
  interface PhonenumberInput {
    'defaultCountry': CountryCode;
    'value': string;
  }
}

declare global {


  interface HTMLPhonenumberInputElement extends Components.PhonenumberInput, HTMLStencilElement {}
  var HTMLPhonenumberInputElement: {
    prototype: HTMLPhonenumberInputElement;
    new (): HTMLPhonenumberInputElement;
  };
  interface HTMLElementTagNameMap {
    'phonenumber-input': HTMLPhonenumberInputElement;
  }
}

declare namespace LocalJSX {
  interface PhonenumberInput {
    'defaultCountry'?: CountryCode;
    'onPhoneNumberInput'?: (event: CustomEvent<any>) => void;
    'onPhoneNumberInvalidated'?: (event: CustomEvent<any>) => void;
    'onPhoneNumberValidated'?: (event: CustomEvent<any>) => void;
    'value'?: string;
  }

  interface IntrinsicElements {
    'phonenumber-input': PhonenumberInput;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'phonenumber-input': LocalJSX.PhonenumberInput & JSXBase.HTMLAttributes<HTMLPhonenumberInputElement>;
    }
  }
}


